# Generated by Django 6.0.5 on 2026-05-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(help_text='GitHub username or org name', max_length=255)),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('full_name', models.CharField(help_text='owner/name', max_length=512, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable reviews for this repo')),
                ('webhook_secret', models.CharField(blank=True, help_text='GitHub webhook secret', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField(help_text='GitHub PR number')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(help_text='GitHub username of PR author', max_length=255)),
                ('base_branch', models.CharField(default='main', max_length=255)),
                ('head_branch', models.CharField(max_length=255)),
                ('github_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('repository', 'pr_number')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='High-level summary of the PR')),
                ('bugs', models.JSONField(default=list, help_text='List of potential bugs found')),
                ('suggestions', models.JSONField(default=list, help_text='List of improvement suggestions')),
                ('security_issues', models.JSONField(default=list, help_text='Security concerns')),
                ('complexity_score', models.IntegerField(blank=True, help_text='Estimated complexity score 1-10', null=True)),
                ('overall_verdict', models.CharField(choices=[('approve', 'Approve'), ('request_changes', 'Request Changes'), ('comment', 'Comment Only')], default='comment', max_length=20)),
                ('raw_llm_response', models.TextField(blank=True, help_text='Full raw response from LLM')),
                ('tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('posted_to_github', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_json', models.JSONField(help_text='1536-dim OpenAI embedding vector as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.review')),
            ],
        ),
    ]
